markdown: redcarpet
pygments: true

title: Why Meditation?
baseurl: /trymeditation
cover_image: mountains.jpg

exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]
